---
name: ".jfignore"
guid: "A6363EF3-AEB3-4BC1-8408-243AAE4C1B8B"
version: "1.0.0.1"
targetAbi: "10.9.9.0"
framework: "net8.0"
overview: "Ignore files and folders by .jfignore Files"
description: >
  Ignore specific files and folders by placing .jfignore files inside your library folder.
  The file can be at the root level or inside a sub directory.
category: "General"
owner: "virtualmarc"
artifacts:
- "Jellyfin.Plugin.JFIgnore.dll"
changelog: >
  1.0.0.0: Initial release
  1.0.0.1: Fixed NPE for new Series
